name: deploy-api

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build & push image to ACR
        run: |
          # Login to ACR
          az acr login --name ${{ secrets.AZURE_ACR_NAME }}
          
          # Build Docker image locally
          docker build -t ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/smart-news-api:latest -f server/Dockerfile .
          
          # Push image to ACR
          docker push ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/smart-news-api:latest

      - name: Point Web App to ACR image
        run: |
          az webapp config container set \
            -g ${{ secrets.AZURE_RG }} \
            -n ${{ secrets.AZURE_WEBAPP_NAME }} \
            --docker-custom-image-name ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/smart-news-api:latest \
            --docker-registry-server-url https://${{ secrets.AZURE_ACR_NAME }}.azurecr.io